APP_ID=ca-mockdonalds-mobile-int
MARKET=ca
ENV=int
BASE_URL=https://int-api.mockdonalds.ca
CDN_URL=https://int-cdn.mockdonalds.ca
MENU_BASE_URL=https://int-menu-api.mockdonalds.ca
ORDER_BASE_URL=https://int-order-api.mockdonalds.ca
ACCOUNT_BASE_URL=https://int-account-api.mockdonalds.ca
REWARDS_BASE_URL=https://int-rewards-api.mockdonalds.ca
STORE_BASE_URL=https://int-stores-api.mockdonalds.ca
NUTRITION_URL=https://www.mcdonalds.com/ca/en-ca/about-our-food/nutrition-calculator.html
LOCALE=en-CA
CURRENCY=CAD
