APP_ID=ca-sampleplatter-mobile-int
MARKET=ca
ENV=int
BASE_URL=https://int-api.sampleplatter.ca
CDN_URL=https://int-cdn.sampleplatter.ca
MENU_BASE_URL=https://int-menu-api.sampleplatter.ca
ORDER_BASE_URL=https://int-order-api.sampleplatter.ca
ACCOUNT_BASE_URL=https://int-account-api.sampleplatter.ca
REWARDS_BASE_URL=https://int-rewards-api.sampleplatter.ca
STORE_BASE_URL=https://int-stores-api.sampleplatter.ca
LOCALE=en-CA
CURRENCY=CAD
