APP_ID=ca-mockdonalds-mobile-mte
MARKET=ca
ENV=mte
BASE_URL=https://mte-api.mockdonalds.ca
CDN_URL=https://mte-cdn.mockdonalds.ca
MENU_BASE_URL=https://mte-menu-api.mockdonalds.ca
ORDER_BASE_URL=https://mte-order-api.mockdonalds.ca
ACCOUNT_BASE_URL=https://mte-account-api.mockdonalds.ca
REWARDS_BASE_URL=https://mte-rewards-api.mockdonalds.ca
STORE_BASE_URL=https://mte-stores-api.mockdonalds.ca
LOCALE=en-CA
CURRENCY=CAD
