APP_ID=ca-sampleplatter-mobile-mte
MARKET=ca
ENV=mte
BASE_URL=https://mte-api.sampleplatter.ca
CDN_URL=https://mte-cdn.sampleplatter.ca
MENU_BASE_URL=https://mte-menu-api.sampleplatter.ca
ORDER_BASE_URL=https://mte-order-api.sampleplatter.ca
ACCOUNT_BASE_URL=https://mte-account-api.sampleplatter.ca
REWARDS_BASE_URL=https://mte-rewards-api.sampleplatter.ca
STORE_BASE_URL=https://mte-stores-api.sampleplatter.ca
LOCALE=en-CA
CURRENCY=CAD
