APP_ID=ca-sampleplatter-mobile
MARKET=ca
ENV=prod
BASE_URL=https://api.sampleplatter.ca
CDN_URL=https://cdn.sampleplatter.ca
MENU_BASE_URL=https://menu-api.sampleplatter.ca
ORDER_BASE_URL=https://order-api.sampleplatter.ca
ACCOUNT_BASE_URL=https://account-api.sampleplatter.ca
REWARDS_BASE_URL=https://rewards-api.sampleplatter.ca
STORE_BASE_URL=https://stores-api.sampleplatter.ca
LOCALE=en-CA
CURRENCY=CAD
