APP_ID=ca-mockdonalds-mobile
MARKET=ca
ENV=prod
BASE_URL=https://api.mockdonalds.ca
CDN_URL=https://cdn.mockdonalds.ca
MENU_BASE_URL=https://menu-api.mockdonalds.ca
ORDER_BASE_URL=https://order-api.mockdonalds.ca
ACCOUNT_BASE_URL=https://account-api.mockdonalds.ca
REWARDS_BASE_URL=https://rewards-api.mockdonalds.ca
STORE_BASE_URL=https://stores-api.mockdonalds.ca
LOCALE=en-CA
CURRENCY=CAD
