APP_ID=us-mockdonalds-mobile-int
MARKET=us
ENV=int
BASE_URL=https://int-api.mockdonalds.com
CDN_URL=https://int-cdn.mockdonalds.com
MENU_BASE_URL=https://int-menu-api.mockdonalds.com
ORDER_BASE_URL=https://int-order-api.mockdonalds.com
ACCOUNT_BASE_URL=https://int-account-api.mockdonalds.com
REWARDS_BASE_URL=https://int-rewards-api.mockdonalds.com
STORE_BASE_URL=https://int-stores-api.mockdonalds.com
LOCALE=en-US
CURRENCY=USD
