APP_ID=us-mockdonalds-mobile-mte
MARKET=us
ENV=mte
BASE_URL=https://mte-api.mockdonalds.com
CDN_URL=https://mte-cdn.mockdonalds.com
MENU_BASE_URL=https://mte-menu-api.mockdonalds.com
ORDER_BASE_URL=https://mte-order-api.mockdonalds.com
ACCOUNT_BASE_URL=https://mte-account-api.mockdonalds.com
REWARDS_BASE_URL=https://mte-rewards-api.mockdonalds.com
STORE_BASE_URL=https://mte-stores-api.mockdonalds.com
LOCALE=en-US
CURRENCY=USD
