APP_ID=us-sampleplatter-mobile-mte
MARKET=us
ENV=mte
BASE_URL=https://mte-api.sampleplatter.com
CDN_URL=https://mte-cdn.sampleplatter.com
MENU_BASE_URL=https://mte-menu-api.sampleplatter.com
ORDER_BASE_URL=https://mte-order-api.sampleplatter.com
ACCOUNT_BASE_URL=https://mte-account-api.sampleplatter.com
REWARDS_BASE_URL=https://mte-rewards-api.sampleplatter.com
STORE_BASE_URL=https://mte-stores-api.sampleplatter.com
LOCALE=en-US
CURRENCY=USD
