APP_ID=us-mockdonalds-mobile
MARKET=us
ENV=prod
BASE_URL=https://api.mockdonalds.com
CDN_URL=https://cdn.mockdonalds.com
MENU_BASE_URL=https://menu-api.mockdonalds.com
ORDER_BASE_URL=https://order-api.mockdonalds.com
ACCOUNT_BASE_URL=https://account-api.mockdonalds.com
REWARDS_BASE_URL=https://rewards-api.mockdonalds.com
STORE_BASE_URL=https://stores-api.mockdonalds.com
LOCALE=en-US
CURRENCY=USD
