APP_ID=de-sampleplatter-mobile-int
MARKET=de
ENV=int
BASE_URL=https://int-api.sampleplatter.de
CDN_URL=https://int-cdn.sampleplatter.de
MENU_BASE_URL=https://int-menu-api.sampleplatter.de
ORDER_BASE_URL=https://int-order-api.sampleplatter.de
ACCOUNT_BASE_URL=https://int-account-api.sampleplatter.de
REWARDS_BASE_URL=https://int-rewards-api.sampleplatter.de
STORE_BASE_URL=https://int-stores-api.sampleplatter.de
LOCALE=de-DE
CURRENCY=EUR
