APP_ID=de-sampleplatter-mobile-mte
MARKET=de
ENV=mte
BASE_URL=https://mte-api.sampleplatter.de
CDN_URL=https://mte-cdn.sampleplatter.de
MENU_BASE_URL=https://mte-menu-api.sampleplatter.de
ORDER_BASE_URL=https://mte-order-api.sampleplatter.de
ACCOUNT_BASE_URL=https://mte-account-api.sampleplatter.de
REWARDS_BASE_URL=https://mte-rewards-api.sampleplatter.de
STORE_BASE_URL=https://mte-stores-api.sampleplatter.de
LOCALE=de-DE
CURRENCY=EUR
