APP_ID=de-sampleplatter-mobile
MARKET=de
ENV=prod
BASE_URL=https://api.sampleplatter.de
CDN_URL=https://cdn.sampleplatter.de
MENU_BASE_URL=https://menu-api.sampleplatter.de
ORDER_BASE_URL=https://order-api.sampleplatter.de
ACCOUNT_BASE_URL=https://account-api.sampleplatter.de
REWARDS_BASE_URL=https://rewards-api.sampleplatter.de
STORE_BASE_URL=https://stores-api.sampleplatter.de
LOCALE=de-DE
CURRENCY=EUR
