APP_NAME=MockDonalds
APP_ID=
MARKET=us
ENV=int
BASE_URL=
CDN_URL=
MENU_BASE_URL=
ORDER_BASE_URL=
ACCOUNT_BASE_URL=
REWARDS_BASE_URL=
STORE_BASE_URL=
NUTRITION_URL=https://www.mcdonalds.com/us/en-us/about-our-food/nutrition-calculator.html
LOCALE=en-US
CURRENCY=USD
