APP_ID=au-sampleplatter-mobile-int
MARKET=au
ENV=int
BASE_URL=https://int-api.sampleplatter.com.au
CDN_URL=https://int-cdn.sampleplatter.com.au
MENU_BASE_URL=https://int-menu-api.sampleplatter.com.au
ORDER_BASE_URL=https://int-order-api.sampleplatter.com.au
ACCOUNT_BASE_URL=https://int-account-api.sampleplatter.com.au
REWARDS_BASE_URL=https://int-rewards-api.sampleplatter.com.au
STORE_BASE_URL=https://int-stores-api.sampleplatter.com.au
LOCALE=en-AU
CURRENCY=AUD
