APP_ID=au-mockdonalds-mobile-mte
MARKET=au
ENV=mte
BASE_URL=https://mte-api.mockdonalds.com.au
CDN_URL=https://mte-cdn.mockdonalds.com.au
MENU_BASE_URL=https://mte-menu-api.mockdonalds.com.au
ORDER_BASE_URL=https://mte-order-api.mockdonalds.com.au
ACCOUNT_BASE_URL=https://mte-account-api.mockdonalds.com.au
REWARDS_BASE_URL=https://mte-rewards-api.mockdonalds.com.au
STORE_BASE_URL=https://mte-stores-api.mockdonalds.com.au
LOCALE=en-AU
CURRENCY=AUD

PHONE_COUNTRY_DIAL_CODE=+61
