APP_ID=au-mockdonalds-mobile
MARKET=au
ENV=prod
BASE_URL=https://api.mockdonalds.com.au
CDN_URL=https://cdn.mockdonalds.com.au
MENU_BASE_URL=https://menu-api.mockdonalds.com.au
ORDER_BASE_URL=https://order-api.mockdonalds.com.au
ACCOUNT_BASE_URL=https://account-api.mockdonalds.com.au
REWARDS_BASE_URL=https://rewards-api.mockdonalds.com.au
STORE_BASE_URL=https://stores-api.mockdonalds.com.au
LOCALE=en-AU
CURRENCY=AUD

PHONE_COUNTRY_DIAL_CODE=+61
