package com.mockdonalds.app.buildtooling.ksp.fakeappbuildconfig

import com.google.devtools.ksp.getDeclaredProperties
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.google.devtools.ksp.symbol.KSType
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.addOriginatingKSFile
import com.squareup.kotlinpoet.ksp.toTypeName
import com.squareup.kotlinpoet.ksp.writeTo

/**
 * Generates `class FakeAppBuildConfig : AppBuildConfig` into `:core:build-config:test` from the
 * `AppBuildConfig` interface. Every property becomes an `override var` seeded with a type-appropriate
 * empty default ("" / 0 / false). Tests construct a no-arg `FakeAppBuildConfig()` and mutate only the
 * fields they care about.
 */
class AppBuildConfigFakeProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    private var generated = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (generated) return emptyList()

        val facade = resolver.findClass(APP_BUILD_CONFIG_FQN) ?: return emptyList()

        val properties = facade.getDeclaredProperties().toList()
        if (properties.isEmpty()) {
            logger.error("AppBuildConfig has no declared properties — cannot generate fake.", facade)
            return emptyList()
        }

        writeFile(properties, containingFile = facade)
        generated = true
        return emptyList()
    }

    private fun Resolver.findClass(fqn: String): KSClassDeclaration? =
        getClassDeclarationByName(getKSNameFromString(fqn))

    private fun writeFile(properties: List<KSPropertyDeclaration>, containingFile: KSClassDeclaration) {
        val appBuildConfig = ClassName(FACADE_PACKAGE, "AppBuildConfig")
        val appScope = ClassName(METRO_PACKAGE, "AppScope")
        val contributesBinding = ClassName(METRO_PACKAGE, "ContributesBinding")

        val propertySpecs = properties.map { property ->
            val propertyName = property.simpleName.asString()
            val typeRef = property.type.resolve()
            val typeName = typeRef.toTypeName()
            val initializer = defaultInitializer(typeRef)
                ?: error(
                    "Unsupported type for AppBuildConfig.$propertyName: $typeName. " +
                        "AppBuildConfigFakeProcessor covers String, Int, Long, Short, Byte, " +
                        "Boolean, Double, Float, Char, and any nullable type.",
                )
            PropertySpec.builder(propertyName, typeName, KModifier.OVERRIDE)
                .mutable(true)
                .initializer(initializer)
                .build()
        }

        val classBuilder = TypeSpec.classBuilder(FAKE_CLASS_NAME)
            .addSuperinterface(appBuildConfig)
            .addAnnotation(
                AnnotationSpec.builder(contributesBinding)
                    .addMember("%T::class", appScope)
                    .build(),
            )
            .addKdoc(
                "Auto-generated by AppBuildConfigFakeProcessor. Do not edit by hand — " +
                    "every AppBuildConfig property becomes an `override var` with a type-empty default. " +
                    "Tests set only the fields they care about.",
            )
            .addProperties(propertySpecs)

        containingFile.containingFile?.let { classBuilder.addOriginatingKSFile(it) }

        FileSpec.builder(TEST_PACKAGE, FAKE_CLASS_NAME)
            .addFileComment("Generated by AppBuildConfigFakeProcessor. Do not edit.")
            .addType(classBuilder.build())
            .build()
            .writeTo(codeGenerator, aggregating = false)
    }

    private fun defaultInitializer(type: KSType): CodeBlock? {
        if (type.isMarkedNullable) return CodeBlock.of("null")
        val name = type.declaration.qualifiedName?.asString() ?: return null
        return when (name) {
            "kotlin.String" -> CodeBlock.of("%S", "")
            "kotlin.Int", "kotlin.Short", "kotlin.Byte" -> CodeBlock.of("0")
            "kotlin.Long" -> CodeBlock.of("0L")
            "kotlin.Boolean" -> CodeBlock.of("false")
            "kotlin.Double" -> CodeBlock.of("0.0")
            "kotlin.Float" -> CodeBlock.of("0f")
            "kotlin.Char" -> CodeBlock.of("' '")
            else -> null
        }
    }

    private companion object {
        const val FACADE_PACKAGE = "com.mockdonalds.app.core.buildconfig"
        const val TEST_PACKAGE = "com.mockdonalds.app.core.buildconfig.test"
        const val METRO_PACKAGE = "dev.zacsweers.metro"
        const val APP_BUILD_CONFIG_FQN = "$FACADE_PACKAGE.AppBuildConfig"
        const val FAKE_CLASS_NAME = "FakeAppBuildConfig"
    }
}
