APP_ID=core-sampleplatter-mobile-mte
MARKET=core
ENV=mte
BASE_URL=https://core-mte-api.sampleplatter.com
CDN_URL=https://core-mte-cdn.sampleplatter.com
MENU_BASE_URL=https://core-mte-menu-api.sampleplatter.com
ORDER_BASE_URL=https://core-mte-order-api.sampleplatter.com
ACCOUNT_BASE_URL=https://core-mte-account-api.sampleplatter.com
REWARDS_BASE_URL=https://core-mte-rewards-api.sampleplatter.com
STORE_BASE_URL=https://core-mte-stores-api.sampleplatter.com
LOCALE=en-US
CURRENCY=USD
