APP_ID=core-sampleplatter-mobile
MARKET=core
ENV=prod
BASE_URL=https://core-api.sampleplatter.com
CDN_URL=https://core-cdn.sampleplatter.com
MENU_BASE_URL=https://core-menu-api.sampleplatter.com
ORDER_BASE_URL=https://core-order-api.sampleplatter.com
ACCOUNT_BASE_URL=https://core-account-api.sampleplatter.com
REWARDS_BASE_URL=https://core-rewards-api.sampleplatter.com
STORE_BASE_URL=https://core-stores-api.sampleplatter.com
LOCALE=en-US
CURRENCY=USD
