APP_ID=core-mockdonalds-mobile-int
MARKET=core
ENV=int
BASE_URL=https://core-int-api.mockdonalds.com
CDN_URL=https://core-int-cdn.mockdonalds.com
MENU_BASE_URL=https://core-int-menu-api.mockdonalds.com
ORDER_BASE_URL=https://core-int-order-api.mockdonalds.com
ACCOUNT_BASE_URL=https://core-int-account-api.mockdonalds.com
REWARDS_BASE_URL=https://core-int-rewards-api.mockdonalds.com
STORE_BASE_URL=https://core-int-stores-api.mockdonalds.com
LOCALE=en-US
CURRENCY=USD
