APP_ID=core-mockdonalds-mobile
MARKET=core
ENV=prod
BASE_URL=https://core-api.mockdonalds.com
CDN_URL=https://core-cdn.mockdonalds.com
MENU_BASE_URL=https://core-menu-api.mockdonalds.com
ORDER_BASE_URL=https://core-order-api.mockdonalds.com
ACCOUNT_BASE_URL=https://core-account-api.mockdonalds.com
REWARDS_BASE_URL=https://core-rewards-api.mockdonalds.com
STORE_BASE_URL=https://core-stores-api.mockdonalds.com
LOCALE=en-US
CURRENCY=USD
