APP_ID=core-mockdonalds-mobile-mte
MARKET=core
ENV=mte
BASE_URL=https://core-mte-api.mockdonalds.com
CDN_URL=https://core-mte-cdn.mockdonalds.com
MENU_BASE_URL=https://core-mte-menu-api.mockdonalds.com
ORDER_BASE_URL=https://core-mte-order-api.mockdonalds.com
ACCOUNT_BASE_URL=https://core-mte-account-api.mockdonalds.com
REWARDS_BASE_URL=https://core-mte-rewards-api.mockdonalds.com
STORE_BASE_URL=https://core-mte-stores-api.mockdonalds.com
LOCALE=en-US
CURRENCY=USD
