APP_ID=core-sampleplatter-mobile-int
MARKET=core
ENV=int
BASE_URL=https://core-int-api.sampleplatter.com
CDN_URL=https://core-int-cdn.sampleplatter.com
MENU_BASE_URL=https://core-int-menu-api.sampleplatter.com
ORDER_BASE_URL=https://core-int-order-api.sampleplatter.com
ACCOUNT_BASE_URL=https://core-int-account-api.sampleplatter.com
REWARDS_BASE_URL=https://core-int-rewards-api.sampleplatter.com
STORE_BASE_URL=https://core-int-stores-api.sampleplatter.com
LOCALE=en-US
CURRENCY=USD
