APP_ID=de-mockdonalds-mobile-dev
MARKET=de
ENV=dev
BASE_URL=https://dev-api.mockdonalds.de
CDN_URL=https://dev-cdn.mockdonalds.de
MENU_BASE_URL=https://dev-menu-api.mockdonalds.de
ORDER_BASE_URL=https://dev-order-api.mockdonalds.de
ACCOUNT_BASE_URL=https://dev-account-api.mockdonalds.de
REWARDS_BASE_URL=https://dev-rewards-api.mockdonalds.de
STORE_BASE_URL=https://dev-stores-api.mockdonalds.de
LOCALE=de-DE
CURRENCY=EUR
