APP_ID=us-mockdonalds-mobile-dev
MARKET=us
ENV=dev
BASE_URL=https://dev-api.mockdonalds.com
CDN_URL=https://dev-cdn.mockdonalds.com
MENU_BASE_URL=https://dev-menu-api.mockdonalds.com
ORDER_BASE_URL=https://dev-order-api.mockdonalds.com
ACCOUNT_BASE_URL=https://dev-account-api.mockdonalds.com
REWARDS_BASE_URL=https://dev-rewards-api.mockdonalds.com
STORE_BASE_URL=https://dev-stores-api.mockdonalds.com
LOCALE=en-US
CURRENCY=USD
