import Foundation

public enum RegistryEmitter {
    public static func emit(entries: [CircuitInjectEntry]) -> String {
        let sorted = entries.sorted { lhs, rhs in
            if lhs.isDebugOnly != rhs.isDebugOnly { return !lhs.isDebugOnly }
            return lhs.viewType < rhs.viewType
        }

        var output = """
        // Generated by CircuitFactoryRegistryPlugin. Do not edit.
        import SwiftUI
        import ComposeApp

        extension CircuitIos {
            static func generatedFactories() -> [UiFactory] {
                var factories: [UiFactory] = [

        """

        for entry in sorted where !entry.isDebugOnly {
            output += "            \(factoryLine(entry)),\n"
        }

        output += "        ]\n"

        let debugEntries = sorted.filter { $0.isDebugOnly }
        if !debugEntries.isEmpty {
            output += "        #if DEBUG\n"
            for entry in debugEntries {
                output += "        factories.append(\(factoryLine(entry)))\n"
            }
            output += "        #endif\n"
        }

        output += """
                return factories
            }
        }

        """
        return output
    }

    private static func factoryLine(_ entry: CircuitInjectEntry) -> String {
        "ScreenUiFactory<\(entry.screenType), \(entry.stateType)> { \(entry.viewType)(state: $0) }"
    }
}
